=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/bundle.dtd
<!--
  - CCC XML Resource Bundle DTD
  -
  - author: Ralf Westbrock
  - author: Gerd Langer
  -
  - version: 1.0
-->

<!--
    The DTD describes the structure used for XML based resource bundles.
    XML resource bundles are the resource bundle type generally used in CCC.
    The resource bundle is capable to replace properties files resource bundles.
    They not only provide a key/value pair per entry, but also allow external
    translators to differentiate between translation relevant texts,
    locale-sensitive settings and locale-independent configurations.

    The body of a bundle contains several translation units. A translation
    unit has a specific type and is identified by a key. Possible types are:
    <ul>
    <li><i>label</i></li>
    <li><i>message</i></li>
    <li><i>setting</i></li>
    <li><i>configuration</i></li>
    <li><i>menuitem</i> (used by PDE application client only)</li>
    <li><i>table</i> (used by PDE application client only)</li>
    <li><i>caption</i> (used by PDE application client only)</li>
    <li><i>column</i> (used by PDE application client only)</li>
    <li><i>componenthelp</i> (used only in PDE application client)</li>
    </ul>
    The following elements of a XML based resource bundle have to translated:
    <ul>
    <li>each content</li>
    <li>values of the attributes
        <ul>
        <li><i>mnemonic</i></li>
        <li><i>accelerator</i></li>
        <li><i>tooltip</i></li>
        </ul>
    </li>
    </ul>
-->

<!-- stateattr -->
<!--
  - The stateattr entity is used to define the 'state' attribute.
  - The 'state' attribute on the other hand is used to mark new
  - entries.
-->
<!ENTITY % stateattr "state (new|approved) #REQUIRED">

<!-- root element -->
<!--
  - the version specifies the bundle version which currently is "1.0"
-->
    <!ELEMENT bundle            (header, body) >
    <!ATTLIST bundle
            version             CDATA               #REQUIRED >

<!-- header of a resource bundle document -->
<!--
  - The header contains some meta information about the bundle.
  -
  - author        defines the developer that wrote the file
  - creationdate  date when the bundle was created YY-MM-DD
  - changedate    date of last change YY-MM-DD
-->
    <!ELEMENT header            EMPTY >
    <!ATTLIST header
            author              CDATA               #IMPLIED
            creationdate        CDATA               #IMPLIED
            changedate          CDATA               #IMPLIED >

<!-- body of a resource bundle document -->
<!--
  - The body contains all elements defined by the bundle.
-->
    <!ELEMENT body              (label
                                |menuitem
                                |message
                                |table
                                |setting
                                |configuration
                                |componenthelp)* >
    <!-- not attributes -->

<!-- label -->
<!--
  - labels are used to translate screen elements that include
  - a mnemonic (underlined character) and are typically used
  - as captions of a data field (e.g. a text field).
-->
    <!ELEMENT label             (#PCDATA) >
    <!ATTLIST label
            key                 ID                  #REQUIRED
            helpID              CDATA               #IMPLIED
            mnemonic            CDATA               #IMPLIED
            %stateattr; >

<!-- message -->
<!--
  - messages are used for screen elements that simply display a text,
  - but do not need a help key or a mnemonic.
-->
    <!ELEMENT message           (#PCDATA) >
    <!ATTLIST message
            key                 ID                  #REQUIRED
            %stateattr; >

<!-- setting -->
<!--
  - settings are used to specify elements that might be localized
  - but are normally not displayed as text on the screen directly.
  - E.g. a path to an icon file.
-->
    <!ELEMENT setting           EMPTY >
    <!ATTLIST setting
            key                 ID                  #REQUIRED
            value               CDATA               #REQUIRED
            %stateattr; >

<!-- configuration -->
<!--
  - configurations are used to mark elements that are not localized
  - and are typically used for technical purposes.
  - E.g. a classname or a link to a file.
-->
    <!ELEMENT configuration     EMPTY >
    <!ATTLIST configuration
            key                 ID                  #REQUIRED
            constant            CDATA               #REQUIRED >

<!-- menuitem -->
<!--
  - menuitems are used to translate the elements wihtin a menu.
  - In addition to labels, menuitems have an optional accelerator key
  - (e.g. "ctrl  C", "shift F1") and a tooltip that is used when
  - the item is diplayed as toolbar button.
-->
    <!ELEMENT menuitem          (#PCDATA) >
    <!ATTLIST menuitem
            key                 ID                  #REQUIRED
            helpID              CDATA               #IMPLIED
            mnemonic            CDATA               #IMPLIED
            accelerator         CDATA               #IMPLIED
            tooltip             CDATA               #IMPLIED
            %stateattr; >

<!-- table -->
<!--
  - A table element collects all entries necessary to translate a
  - a table and its column headers.
-->
    <!ELEMENT table             (caption, column*) >
    <!ATTLIST table
            key                 ID                  #REQUIRED
            helpID              CDATA               #IMPLIED >

<!-- caption -->
<!--
  - Used to localize the table's caption.
  - Note: the key is already defined in the table entry itself.
-->
    <!ELEMENT caption           (#PCDATA) >
    <!ATTLIST caption
            %stateattr; >

<!-- column -->
<!--
  - For each column of the table a column element is expected.
-->
    <!ELEMENT column            (#PCDATA) >
    <!ATTLIST column
            key                 ID                  #REQUIRED
            %stateattr; >

<!-- componenthelp -->
<!--
  - The component help can be used to specify helpIDs for each
  - key used for the component.
-->
    <!ELEMENT componenthelp     EMPTY >
    <!ATTLIST componenthelp
            key                 ID                  #REQUIRED
            helpID              CDATA               #REQUIRED >

<!-- EOF -->

=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/FUNC_FRMWK_CMN_ErrorDictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bundle PUBLIC "bundle.dtd" "bundle.dtd">

<bundle version="1.0">
    <header author="Dmitri Geller"
            creationdate="11-06-2003"/>
    <body>
                     
		<setting key="id001" value="Precondition failed: {0} isn't set in {1}" state="new" />

<!-- SOITool -->

		<setting key="id0002" value="Can't find file {0}. Details: {1}" state="new" />
		<setting key="id0003" value="Error when reading file {0}. Details: {1}" state="new" />
		<setting key="id0004" value="Mandatory command-line argument missing: {0}" state="new" />
		<setting key="id0005" value="Wrong mode: {0}. Allowed modes: {1}" state="new" />
		<setting key="id0006" value="Error when creating instance of class {0}. Details: {1}" state="new" />				
		<setting key="id0007" value="Service object {0} can't be found. Check 'so' atribute of COMMAND or TX_COMMIT tag" state="new" />

<!--XML -->
		<!--IOException, SAXException-->
        <setting key="id0008" value="General XML error. File: {0}. Details: {1}" state="new" />
		<setting key="id0009" value="Error reading/writing tag {0} with attribute {1} in the XML file. Details: {2}" state="new" />
		<setting key="id0011" value="Unknown action: {0}. Only 'B', 'C', 'R', 'V' allowed" state="new" />
        <!--SAXParseException-->
		<setting key="id0012" value="XML parse error. File: {0}, Line: {1}, Message: {2}" state="new" />
		<!--UnsupportedEncodingException-->
        <setting key="id0013" value="Unsupported encoding {0} in output XML file. Details: {1}" state="new" />

		<setting key="id0050" value="Error when creating instance of class {0}. \nDetails: {1}" state="new" />
	
<!-- Exceptions in common part of CORBA transport layer -->		
		
		<!--Naming service/CORBA  -->
		<setting key="id100" value="The naming service could not be found. Check your environment, especially settings in /resource/orb.properties  Detailed error message: {0}. " state="new" />
		<setting key="id101" value="Can not find naming service using 'resolve_initial_references'" state="new" />
		<setting key="id102" value="Can not resolve_initial_references() for name {0}. Details: {1}" state="new" />
		<setting key="id103" value="When searching name {0} in the naming service corba exception happens: {1}" state="new" />
		<setting key="id104" value="CORBA error when finding public naming context. Details: {0}" state="new" />
		<setting key="id105" value="CORBA error when finding private naming context. Details: {0}" state="new" />
		<setting key="id106" value="CORBA error when creating the naming context. Details: {0}" state="new" />
		<setting key="id0107" value="Can not obtain RootPOA. Details: {0}" state="new" />
		<setting key="id0108" value="Can not register a CORBA object named {0} in the naming service under name: {1}. Details: {2}" state="new" />
		<setting key="id0109" value="Specified reference doesn't point to valid ServiceRootI. Details: {0}" state="new" />
		<setting key="id0110" value="Naming context {0} isn't found" state="new" />
		<setting key="id0111" value="Server {0} isn't found in {1}" state="new" />
		<setting key="id0112" value="CORBA error when activating a servant. Details: {0}" state="new" />
		<setting key="id0113" value="CORBA error when deactivating a servant. Details: {0}" state="new" />
		<setting key="id0114" value="Invalid context name {0} submitted to naming service. Details: {1}" state="new" />
		<setting key="id0115" value="Can not access a CORBA object in the naming service under name: {0}. Details: {1}" state="new" />
		<setting key="id0116" value="Can not unregister a CORBA object from the naming service under name: {0}. Details: {1}" state="new" />
		<setting key="id0120" value="CORBA system exception {0} when {1}" state="new" />

		<!-- Exceptions in SOI/SVLObject processing -->
		<!-- InvalidParameterTypeException -->
		<setting key="id0201" value="Incorrect access to an attribute stored in SVLobject. Access method: {0} Attribut {1}" state="new" />
		<!--ParameterListException -->
		<setting key="id0202" value="Error processing metainformation. ParameterList could not be retrieved from a remote SOI implementation. SOIName {0} SOIVersion {1}, Details {2}" state="new" />
		<!--ParameterListException -->
		<setting key="id0203" value="Error processing metainformation. Can't find metainformation for: Command {0}, SOIName {1}, SOIVersion {2}" state="new" />
		<!--ParameterListException -->
		<setting key="id0204" value="ParameterList cannot be transformed into a  sequence NvElementI. Parameter {0} Details {1}" state="new" />
		<!--InvalidParameterTypeException -->
		<setting key="id0205" value="Error when extracting value from Any. Unknown typecode: {0}. Any: {1}" state="new" />
		<!--ParameterListException -->
		<setting key="id0206" value="A sequence of NvElementI can not be transformed in ParameterList. Parameter {0} Unknown typecode: {1}" state="new" />
		<!--ParameterListException -->
		<setting key="id0207" value="A sequence of NvElementI can not be transformed in ParameterList. Parameter {0} is not a sublist" state="new" />
		<!--ComponentException -->
		<setting key="id0208" value="A ServiceAccessor for SOI {0} version {1} should be created first!" state="new" />
		<!--SystemException -->
		<setting key="id0209" value="An instance of the ParameterListLoader should be register before calling AccessorFactory.getServiceAccessor. See ServiceLayerIntrospector.setParameterListLoader" state="new" />
		
		<!-- SignatureMismatchException -->
		<setting key="id0210" value="Value of parameter {0} doesn't match to the method {1}" state="new" />
		<setting key="id0211" value="Parameter {0} should have a list type" state="new" />
		<setting key="id0212" value="Parameter {0} has unknown type {1} (The type isn't defined in SVLType)" state="new" />
		<setting key="id0213" value="Parameter name {0} is not defined in the ParameterList" state="new" />
		<!-- Validation results of SVLObject/NvList -->
		<setting key="id0214" value="Arguments of the command {0} are wrong. Details: {1}" state="new" />
		<setting key="id0215" value="Results of the command {0} are wrong. Details: {1}" state="new" />
		
		<!-- Wrappers for CORBA exceptions -->
		<setting key="id0220" value="Unknown command: {0}" state="new" />
		<setting key="id0221" value="Server for the component/SOI. Name: {0} Version: {1} not available. Check that a server is running and registered in the naming service that supports this SOI." state="new" />
		<setting key="id0222" value="{0}" state="new" />
		<!--SystemException, former ServiceLayerExceptionI -->
		<setting key="id0223" value="Unexpected exception on the server side. Server message: {0}" state="new" />
		
		<!-- OrbManager -->
		<setting key="id0240" value="OrbManager not initialized." state="new" />
		<setting key="id0241" value="Could not start thread for ORB listener." state="new" />

<!-- Exceptions in client side of CORBA transport layer -->

		<!-- AccessorRoot -->
		<setting key="id0301" value="No ServiceFactoryI available. Details: {0}" state="new" />
		<setting key="id0302" value="Could not install client callback. Details: {0}" state="new" />

<!-- 0400-0499 reserved -->		

<!-- Non-SOI Java-related exeptions: 0500-0599 -->		

		<setting key="id0501" value="ObjectID already in persistent state. Primary key values may not be set anymore! ObjectID: {0}" state="new" />			
		<setting key="id0502" value="Cannnot deserialaize. ObjectID: byte array is not a serialized object. Details: {0}" state="new" />
		<setting key="id0503" value="Cannnot serialize. Details: {0}" state="new" />		
		<setting key="id0510" value="Java property {0} is not set" state="new" />		
		<setting key="id0511" value="Can't write log files because directory {0} doesn't exist" state="new" />

<!-- 0600-0650 platform specific -->		
		<setting key="id0600" value="Date conversion from date before January, 1st 1970 not possible on WIN32" state="new" />

    </body>
</bundle>

=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/FUNC_UTIL_ErrorDictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bundle PUBLIC "bundle.dtd" "bundle.dtd">

<bundle version="1.0">
    <header author="Dieter Schneiders"
            creationdate="01-JUN-2003"
            changedate="21-MAY-2004"/>
    <body>        
    
		<setting key="SAXParserError" value="SAX Parser Error: {0}: {1}" state="approved" />
		<setting key="NotInitialized" value="{0} not initialized." state="approved" />
		<setting key="BadFormat" value="The registry entry {0} contains wrong value {1} for the type {2}" state="new" />
		
<!-- exceptions in CORBAAdapter.java -->
		<!-- FUNC_FRMWK_CMN.id001 -->
		<setting key="id001" value="Precondition failed: {0} isn't set in {1}" state="new" />
		<!-- FUNC_FRMWK_CMN.id100 -->
		<setting key="id100" value="The naming service could not be found. Check your environment, especially settings in /resource/orb.properties  Detailed error message: {0}. " state="new" />
		<!--FUNC_FRMWK_CMN.id103 -->
		<setting key="id103" value="When searching name {0} in the naming service corba exception happens: {1}" state="new" />
		<!--FUNC_FRMWK_CMN.id0104 -->
		<setting key="id104" value="CORBA error when finding the naming context. Details: {0}" state="new" />
		<!--FUNC_FRMWK_CMN.id106 -->
		<setting key="id106" value="CORBA error when creating the naming context. Details: {0}" state="new" />
		<!-- FUNC_FRMWK_CMN.id107 -->
		<setting key="id0107" value="Can not obtain RootPOA. Details: {0}" state="new" />
		<!--FUNC_FRMWK_CMN.id0108 -->
		<setting key="id0108" value="Can not register a CORBA object named {0} in the naming service under name: {1}. Details: {2}" state="new" />
		<!--FUNC_FRMWK_CMN.id0112 -->
		<setting key="id0112" value="CORBA error when activating a servant. Details: {0}" state="new" />
		<!--FUNC_FRMWK_CMN.id0113 -->
		<setting key="id0113" value="CORBA error when deactivating a servant. Details: {0}" state="new" />
		<!--FUNC_FRMWK_SRV.id0207 -->
		<setting key="id0207" value="Can't register server in the naming service. Server named {0} already exists in context {1}" state="new" />
		<!--FUNC_FRMWK_SRV.id0202 -->
		<setting key="id0202" value="File {0} not found in {1}" state="new" />
		<!--FUNC_FRMWK_SRV.id0203 -->
		<setting key="id0203" value="Error reading file {0}. Details: {1}" state="new" />
		
<!-- Logging-related exeptions: 0500-0569 -->
		<setting key="id0500" value="Can't create log directory {0}" state="new" />
		<setting key="id0501" value="Can't write log files because {0} is not a valid directory" state="new" />

<!-- Java reflection exceptions: 0570-0589 -->
<!-- PN 00308727 : old : pClass in null-->
		<setting key="id0570" value="pClass is null" state="new" />
		<setting key="id0571" value="Can't create a new instance of class {0}. Details: {1}" state="new" />
						
				
<!-- Command-line exceptions: 0590-0599 -->
		<setting key="id0590" value="Mandatory command line parameter missing: {0}" state="new" />
						
<!-- CORBA-related exeptions: 0600-0699 -->
		<setting key="id0600" value="Can not access a CORBA object in the naming service under name: {0}. Details: {1}" state="new" />
		<setting key="id0601" value="CORBA error when creating the naming context. Details: {0}" state="new" />
		<setting key="id0602" value="Can not register a CORBA object named {0} in the naming service under name: {1}. Details: {2}" state="new" />
		<setting key="id0603" value="Can not unregister a CORBA object from the naming service under name: {0}. Details: {1}" state="new" />
		<setting key="id0604" value="Can not find naming service using 'resolve_initial_references'" state="new" />
		<setting key="id0605" value="Can not resolve_initial_references() for name {0}. Details: {1}" state="new" />
		<setting key="id0606" value="CORBA system exception {0} when {1}" state="new" />
		<setting key="id0607" value="OrbManager not initialized." state="new" />
		<setting key="id0608" value="Could not start thread for ORB listener." state="new" />


    </body>
</bundle>

=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/SECURITY_ErrorDictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bundle PUBLIC "bundle.dtd" "bundle.dtd">
<!--
  - 
-->

<bundle version="1.0">
    <header author="Dmitri Geller"
            creationdate="28-05-2004"/>
    <body>
		<!-- 
		1-9
		Security server: setup problems
		 -->
		<setting key='S002' value="Baseline setup error, MODULES_HIERARCHY contains more than {0} nested levels (circular references?)" state="new" />
		<setting key='S003' value="Database error during initialization of security subsystem. Vendor code: {0} SQLState: {1} Details {2}" state="new" />
		<setting key='S004' value="This function is not availiable because security turned off in server" state="new" />
		<!-- Begin PN00300362 chenf -->
		<setting key='S005' value="Wrong security setup. User: {0} isn't found in database." state="new" />
		<!-- End PN00300362 chenf -->
		<setting key='S006' value="Wrong security setup. Security area {0} isn't found in MODULES table" state="new" />
				
		<!--
        10-89
		Security server: Command problems
		-->
		<setting key='S0011' value="Users and groups can not be specified together" state="new" />
		<setting key='S0012' value="Mandatory parameter {0} is missing" state="new" />
		
		<!--PASSWORD.CHANGE -->
		<setting key='S0021' value="NEW_PASSWORD and CONFIRM_PASSWORD are not the same" state="new" />
		<setting key='S0022' value="Database error when changing password. Details: {0}" state="new" />
		<setting key='S0023' value="OLD_PASSWORD is wrong" state="new" />
		<setting key='S0024' value="The password is invalid. Reuse of old password is not allowed." state="new" />
		<setting key='S0025' value="Maximum password length of {0} characters exceeded" state="new" />
		<setting key='S0026' value="Only printable characters without special characters like umlauts are allowed. (ASCII codes between 32 and 126)" state="new" />
		<setting key='S0027' value="The new password is invalid. The length of password is less than the minimum length: {0}" state="new" />
		<setting key='S0028' value="The new password is invalid. It can not be identical with the user name." state="new" />

		<!--USER_RIGHT.CHECK -->
		<setting key='S0030' value="USERNAME is missing" state="new" />
		<setting key='S0031' value="PASSWORD and NO_PASSWORD_REQUIRED can't be used together" state="new" />
		<setting key='S0032' value="You are not allowed to read permissions of another user without his password: 'PermChangeOnBehalfOfUser' is required to do this" state="new" />
		<setting key="S0033" value="USERNAME without PASSWORD or NO_PASSWORD_REQUIRED is not allowed" state="new" />
		<setting key="S0034" value="{0} is not a valid BSCS user" state="new" />
																
		<!--
		90-99 
		Security checks in common framework
		-->
		<setting key='S090' value="General security restriction: access denied" state="new" />
		
		<!--
		100-200 
		Security checks in server framework
		-->
		<setting key='S0100' value="User: {0} has no access rights for: {1} or users password expired" state="new" />
        <setting key='S0101' value="Wrong user or password" state="new" />
        <setting key='S0102' value="Original user: {0} is not allowed to perform a 'switch user' action. Access right 'PermChangeOnBehalfOfUser' required to do this." state="new" />
        <setting key='S0103' value="Oracle security error. Oracle code: {0}. Oracle message: {1}" state="new" />
    </body>
</bundle>

=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/FUNC_SOP_ErrorDictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bundle PUBLIC "bundle.dtd" "bundle.dtd">

<bundle version="1.0">
    <header author="Dmitri Geller"
            creationdate="31-Jan-06.20:19:11"/>
    <body>

		<!--Java, SOP library -->                     
		<setting key="id100" value="There is no value for key: {0}" state="new" />
		<setting key="id101" value="There is no value for composite key: {0}.{1}" state="new" />

		<!--Java, client-side CORBA classes -->                     
		<setting key="id200" value="CORBA object not found in the Naming Service. Path: {0}" state="new" />
		<setting key="id201" value="Can't narrow CORBA object to a ManagedApplicationI. Details: {0}" state="new" />
		<setting key="id202" value="org.omg.CORBA.SystemException thrown. Details: {0}" state="new" />
		<setting key="id203" value="Wrong query name: {0} " state="new" />
		<setting key="id204" value="Can't read NvElementI. Unknown Typecode: {0}. SensorID:{1} AttributeID:{2} AttributeName:{3} " state="new" />
		
		<!--Java, SOP tool-->
		<setting key="id300" value="Unknown action: {0} " state="new" />
		<setting key="id301" value="Connection: {0} is not supported. Supported connections: CORBA, SNMP" state="new" />
		<setting key="id302" value="Mandatory command-line argument missing: {0}" state="new" />
		
		<!-- C++ ManageableApplication -->
		<setting key="id0400" value="Could not initialize SOP: {0}" state="new" />
		<setting key="id0401" value="Could not properly finalize SOP: {0}" state="new" />
		<setting key="id0402" value="SOP not initialized." state="new" />
		<setting key="id0403" value="SOP not supported." state="new" />
		<setting key="id0404" value="Could not send trap. Application Index {0}, Sensor ID {1}, Trap Code {2}: {3}" state="new" />		

    </body>
</bundle>
