=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/ComponentRegistry.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT ComponentRegistry (Node*)>

<!-- 
The Node of a registry is defined as a section/directory in the Registry tree.  The 
Node can have other Nodes or KeyValue entries.
-->
<!ELEMENT Node (KeyValue|Node)*>
<!ATTLIST Node
    name   CDATA	 	#REQUIRED
>


<!--
The KeyValue element is the leaf in the Registry tree.  
It is the last element of the registry path and contains the value of the Registry entry.
-->
<!ELEMENT KeyValue  EMPTY >
<!ATTLIST KeyValue
    key   CDATA	 	#REQUIRED
    type  (Boolean | Float | Integer | String | Date) "String"
    value CDATA 	#REQUIRED
    comment CDATA	#IMPLIED 
>

=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/FUNC_SOP_Registry.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

<!--
This is a common registry file for following components:
sop/cmn
sop/sensor
-->

<ComponentRegistry>

    <Node name="FUNC_SOP">

        <KeyValue key="SOPNamingRoot" type="String" value="com/lhs/private/sop"
        comment="Root context of SOP servers in CORBA Naming Service."/> 

    </Node>
    

    <Node name="FUNC_FRMWK_SRV">

		<!-- 
		Required for initialization of SOP library in the SFW
		-->
        <Node name="StartupListeners" >
			<KeyValue key="com.lhs.ccb.sop.lib.SOPInitializerSFW" type="String" value="" comment="null"/>
        </Node>

		<!-- 
		For shutdown of SOP library
		-->
        <Node name="ShutdownListeners" >
			<KeyValue key="com.lhs.ccb.sop.lib.SOPInitializerSFW" type="String" value="" comment="null"/>
        </Node>
				
    
    </Node>
</ComponentRegistry>

=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/FUNC_FRMWK_SRV_DB_Registry.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ComponentRegistry PUBLIC "ComponentRegistry.dtd" "ComponentRegistry.dtd" >

<!--
This registry file contains common database- and persistence- related settings
-->
<ComponentRegistry>
    <Node name="FUNC_FRMWK_SRV">

        <!-- Database/JDBC/Embedded SQL/TOPLink related settings-->
        <Node name="Persistence">

			<!-- Settings for the Java wrapper of NEXTFREE stored procedures. -->
			<Node name="NEXTFREE">
				<!-- 
				Specifies fetch size for a particular sequence.
				If a sequence is found in the list than NEXTFREE.GetNumValues with 
				array interface will be used with specified fetch size
				
				If a sequence isn't found in the list than NEXTFREE.GetValue 
				will be used (no array interface and caching)
				 -->
				<Node name="FetchSizePerSequence">
		        </Node>
	        </Node>
				
            <!-- Contains KeyValue entries holding the package names of all packages with
                 persistent classes. Each of the packages listed here is assumed to contain
                 a class 'BOregister', which must add the descriptors of the package to the
                 list of all application descriptors.
            -->
            <Node name="PackageNamesForBORegistry">
            </Node>
            
            <!--Contains a list of reference data classes, that should be refreshed 
                periodically.
             -->
            <Node name="RefreshReferenceData">
            </Node>
            
              <!-- 
           	List of Oracle errors that lead to a reset of the database connection pool.
				    This leads to a reconnect at the next access.
			      -->
            <Node name="OraErrorsToReconnect">
		        <KeyValue key="17002" value="" type="String"/>
		        <KeyValue key="17008" value="" type="String"/>
            </Node>
            
            <!-- 
            List of Oracle error codes returned in case when the database
            is not availiable or restarted.           
            SOI server terminates immediately when Oracle returns such error code
            -->
            <Node name="OraErrorsToTerminate">
		        <KeyValue key="1012" value="" type="String"/>
		        <KeyValue key="1033" value="" type="String"/>
		        <KeyValue key="1034" value="" type="String"/>
		        <KeyValue key="12500" value="" type="String"/>
            </Node>
            
            <!-- 
            At login time these Oracle error codes leads to
            a SecurityException
            -->
            <Node name="OraErrorsSecurity">
		        <KeyValue key="28000" value="" type="String"/>
		        <KeyValue key="28001" value="" type="String"/>
		        <KeyValue key="28002" value="" type="String"/>
		        <KeyValue key="28005" value="" type="String"/>
		        <KeyValue key="28009" value="" type="String"/>
		        <KeyValue key="28011" value="" type="String"/>
		        <KeyValue key="17443" value="" type="String"/>
  		        <KeyValue key="17433" value="" type="String"/>
            </Node>
            
            <!--
            Translation of the Oracle "constraint violation" error codes into
            meaningfull domain error codes.
            -->
            <Node name="OraConstraintViolation">
            	<Node name="OraCodes">
            		<!-- 
            		List of Oracle "constraint violation" error codes 
            		-->
		        	<KeyValue key="00001" value="" type="String"/>
            	</Node>
            	<Node name="constraints">
            		<!-- 
            			key: Oracle constraint
            			value: ErrorCode defined in the error dictionary
            		-->
            	</Node>
            </Node>

        </Node>
    </Node><!-- FUNC_FRMWK_SRV -->
</ComponentRegistry>

=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/WS_Integration.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ComponentRegistry PUBLIC 'ComponentRegistry.dtd' "ComponentRegistry.dtd" >

<ComponentRegistry>
<Node name="FUNC_WCLT">


   <!-- Jaas context.  -->
   <KeyValue key="JaasContext" type="String" value="WSContext" comment="JAAS context to be used"/>

     <!--
	    - Defines the server connection pools that should be used for the application.
	    - Each node inside the ServerConnectionPools contains a configuratrion for a connection pool. con
	    -->

	<Node name="ServerConnectionPools">

		 <!--
	        - The list of the connection pools to be used by the application. This list is
	        - only used as key postfix of  node of individual connection pool configuration.
	        -
	        - Pattern of the constant: <connectionPoolName>[,<connectionPoolName]*
	      -->
	 	 <KeyValue key="ConnectionPoolNames"  type="String"  value="ALU,NICO" comment="Name of the connection pools"/>
	 	 
	 	 <!-- <KeyValue key="DefaultConnectionPoolUser"  type="String"  value="EAI" comment="Name of the default connection pool"/> -->
	<KeyValue key="DefaultConnectionPoolUser"  type="String"  value="ALU" comment="Name of the default connection pool"/>

		 <!--
		   - Specifies the default standard setting of pool. Note :This pool is not created  maintained.
		   - If some options of connection pool is not configured then the settings of DefaultPoolSettings is used.
		  -->

		 <Node name="DefaultPoolSettings">
		      <KeyValue key="ConnectionTimeOut"  type="Integer"  value="100" comment="time out in seconds"/>
		      <KeyValue key="MaximumNumberOfConnections"  type="Integer"  value="5" comment="Maximum no of connection to be created for the pool"/>
		      <KeyValue key="MinimumNumberOfConnections"  type="Integer"  value="1" comment="Minimum no of connection to be created when the pool starts"/>
		      <KeyValue key="NoOfConnectionAttempts"  type="Integer"  value="3" comment="No of attempts to be done by application to get a connection from pool"/>
		      <KeyValue key="ConnectionAttemptInterval"  type="Integer"  value="50" comment="Time interval in milli seconds between two successive interval"/>
		  </Node>


	      <!--
            - The configurations for individual connection pool.
            - For every defined ConnectionPoolName a configuration node must be be defined
            - Pattern of the node: ConnectionPool_<connectionPoolName>
           -->
	  	 
	     <Node name="ConnectionPool_ALU">
	     	         <KeyValue key="BscsUser"  type="String"  value="ALU" comment="Integration User"/>
	     	         <KeyValue key="BscsUserPassword"  type="String"  value="ALU" comment=""/>
	     		     <KeyValue key="ConnectionTimeOut"  type="Integer"  value="100" comment="time out in seconds"/>
	     		     <KeyValue key="MaximumNumberOfConnections"  type="Integer"  value="5" comment="Maximum no of connection to be created for the pool"/>
	     		     <KeyValue key="MinimumNumberOfConnections"  type="Integer"  value="2" comment="Minimum no of connection to be created when the pool starts"/>
	     		     <KeyValue key="NoOfConnectionAttempts"  type="Integer"  value="5" comment="No of attempts to be done by application to get a connection from pool"/>
	     		     <KeyValue key="ConnectionAttemptInterval"  type="Integer"  value="15" comment="Time interval in milli seconds between two successive interval"/>
	     </Node>
	     <Node name="ConnectionPool_NICO">
	     	         <KeyValue key="BscsUser"  type="String"  value="NICO" comment="Integration User"/>
	     	         <KeyValue key="BscsUserPassword"  type="String"  value="nicoleta1" comment=""/>
	     		     <KeyValue key="ConnectionTimeOut"  type="Integer"  value="100" comment="time out in seconds"/>
	     		     <KeyValue key="MaximumNumberOfConnections"  type="Integer"  value="5" comment="Maximum no of connection to be created for the pool"/>
	     		     <KeyValue key="MinimumNumberOfConnections"  type="Integer"  value="2" comment="Minimum no of connection to be created when the pool starts"/>
	     		     <KeyValue key="NoOfConnectionAttempts"  type="Integer"  value="5" comment="No of attempts to be done by application to get a connection from pool"/>
	     		     <KeyValue key="ConnectionAttemptInterval"  type="Integer"  value="15" comment="Time interval in milli seconds between two successive interval"/>
	     </Node>		     
	</Node>


</Node>
</ComponentRegistry>
