=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/SOIDefinition.dtd
<!-- This DTD describes the way complete SOI versions may be defined.
     
     Command versions can be included in the SOI definition 
     using the COMMAND element. Multiple versions of the same command
     can not be included in the same SOI definition.    
-->

<!-- Root element of a SOI definition.
	- soiName, represents the name of the defined SOI, e.g. "OM".
	- soiVersion, represents the version of the defined SOI, e.g. "1.2".
-->
<!ELEMENT SOI ( COMMAND+ )>
<!ATTLIST SOI
	soiName CDATA #REQUIRED
	soiVersion CDATA #REQUIRED
>

<!-- A command version used in a particular SOIVersion.
	 - name, represents the name of the command applicable to a SOIV
	 - version, indicates the version information of the command. No two 
	   versions of the same command can be present in the same SOIV. A particular
	   version of a command can be present in more than one SOIV. 
	 - deprecated, flag indicating if the command (not regarding the version at all)
	   is deprecated in this particular SOIV. That is the normal Java deprecation 
	   semantix.
-->
<!ELEMENT COMMAND EMPTY>
<!ATTLIST COMMAND 
	cmdName CDATA #REQUIRED
	cmdVersion CDATA #REQUIRED
	deprecated (yes|no) "no"
>

=== HamzehAbumaizer/hello-world/webapp/src/main/webapp/WEB-INF/classes/conf/cdf/WS_V2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SOI PUBLIC "SOIDefinition.dtd" "SOIDefinition.dtd">

<SOI soiName="WS" soiVersion="2">

    <COMMAND cmdName="BONUSPOINT_CONVERSION.EXECUTE"    cmdVersion="cmd_1" deprecated="no"/>
<!-- <COMMAND cmdName="CONTRACT.CANCEL"                                     cmdVersion="CMD_1_0" deprecated="no"/> -->
    <COMMAND cmdName="CONTRACT.MOVE"                                    cmdVersion="CMD_1_0" deprecated="no"/>
<COMMAND cmdName="CONTRACT.NEW"                                     cmdVersion="CMD_2_0" deprecated="no"/>
    <COMMAND cmdName="CONTRACT.WRITE"                                   cmdVersion="CMD_2_0" deprecated="no"/>
<COMMAND cmdName="SESSION.CHANGE"                                   cmdVersion="CMD_1_0" deprecated="no"/>
    <COMMAND cmdName="SYSTEM_SETTING.READ"                              cmdVersion="CMD_1_0" deprecated="no"/>

<COMMAND cmdName="CUSTOMER.CREATE"                              cmdVersion="CMD_1_0" deprecated="no"/>
<COMMAND cmdName="CONTRACT.CREATE"                              cmdVersion="CMD_1_0" deprecated="no"/>

<!-- PN00282798 DZI, since the following composite commands are contained in WS_2.xml disabled them here -->
   <!-- Composite Commands start -->
<!-- COMMAND cmdName="CUSTOMER.CREATE"                  cmdVersion="CMD_1_0" deprecated="no" / -->
   <!-- COMMAND cmdName="CUSTOMER.RETRIEVE"                cmdVersion="CMD_1_0" deprecated="no" / -->
<!-- COMMAND cmdName="CONTRACT.CREATE"                  cmdVersion="CMD_1_0" deprecated="no" / -->
   <!-- COMMAND cmdName="CONTRACT.RETRIEVE"                cmdVersion="CMD_1_0" deprecated="no" / -->
<!-- COMMAND cmdName="CUSTOMER_AND_CONTRACT.CREATE"     cmdVersion="CMD_1_0" deprecated="no" / -->
   <!-- Composite Commands end -->
<!-- PN00282798 end -->
</SOI>
"build.xml"
